### ISSUE TITLE
feat: Add support to scan the qr from local image

### ISSUE THREAD

**Issue by arnabsen1729** [kokoye2007/wifi-qr#10]
There might be scenarios when the user has the image of the QR locally in their system. So we can add an option to choose an image and scan the QR from that.

In mobile phones, we have the option for that too.

**Comment by kokoye2007** [comment]
```
$ wifi-qr
	Please use	g for GUI Main Menu 
			c for WiFi QR Create GUI
			t for WiFi QR Create Terminal
			s for QR Scan and Auto Connect WiFi
			q for QR Scan and Connect WiFi GUI
			v for WiFi-QR Version is 0.2
```
![Screenshot from 2022-04-21 19-08-33](https://user-images.githubusercontent.com/3091754/164459869-41afcbd1-3528-4691-b974-e5182fcd90f3.png)

**Comment by arnabsen1729** [comment]
Ya, the first option opens the webcam. But what if the machine doesn't support a webcam or the quality is very low that it doesn't detect the qr.

We can have another option that  calls the `zbarimg`. Like this:

```bash
zbarimg --raw /path/to/image >"$qr_data" 2>/dev/null
```
