### ISSUE TITLE
Password with special characters needs to be unquoted

### ISSUE THREAD

**Issue by sualk** [kokoye2007/wifi-qr#12]
Scan an connect fails if the password contains a special character like ",", eg "123,ab"
In that case the password gets set as "123\,ab", an additional \ is added.

The password and possibly also the SSID needs to be unquoted before further use.

**Comment by kokoye2007** [comment]
I will test and use to hash. It's possible :) 

Thanks for your help.

**Comment by kokoye2007** [comment]
qrencode is strip  
special character < Reserved Characters >
- https://www.rfc-editor.org/rfc/rfc3986#section-2.1
- https://metacpan.org/pod/URI::Encode

**Comment by kokoye2007** [comment]
> qrencode is strip special character < Reserved Characters >
> 
> * https://www.rfc-editor.org/rfc/rfc3986#section-2.1
> * https://metacpan.org/pod/URI::Encode

https://support.idautomation.com/Image-Generator/QR-Code-encoding-the-special-characters-such-as-or/_1876

**Comment by sualk** [comment]
Maybe i did not describe the problem well enough and i also noted that one \ is missing in my initial report.

If you have a WIFI network with some special characters in the password then these characters should be quoted in the QR code as described here: https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11

So the WIFI password is "123,abc", but the QR contains the following "123\\,abc".

Scanning this QR code with wifi-qr will use the password with the additional \ instead of the correct one without the \.
So before using the password data from the QR code an unquoting is required to generate the correct password.

**Comment by kokoye2007** [comment]
Release v0.2-3 
https://github.com/kokoye2007/wifi-qr/releases/tag/0.2-3

**Comment by ls-1N** [comment]
It worked for me with a password that has `@` in it. :+1: 

@kokoye2007 Btw is it intentional that you didn't upload a `.deb` file in the 0.2.3 release?

**Comment by kokoye2007** [comment]
@ls-1N apologies 
I will update ASAP with 
- SSID name instead SSID File Name
- SSID special characters as well. 

next release will be .deb and archive :D 
Thank for your support.

**Comment by kokoye2007** [comment]
> It worked for me with a password that has `@` in it. +1
> 
> @kokoye2007 Btw is it intentional that you didn't upload a `.deb` file in the 0.2.3 release?

https://github.com/kokoye2007/wifi-qr/releases/tag/wifi-qr-0.2-3
