### ISSUE TITLE
QR issue when the SSID has special characters

### ISSUE THREAD

**Issue by ls-1N** [kokoye2007/wifi-qr#15]
Tested from the newest `master` branch directly, without building a deb file.

Issue when the SSID has a special character.
The saved QR code contains this information:
```
WIFI:S:Hoolitsege enda eest \;P:;;
```
The SSID is incorrect (supposed to be `Hoolitsege enda eest :)` in this case) and the password seems to never get added to the QR code.

**Comment by kokoye2007** [comment]
According to this one.
We need to escape strap from special characters from either.
same with SSID and Password

**Comment by kokoye2007** [comment]
@ls-1N Ohhh
I am very naughty.
force push with wrong tag.

**Comment by ls-1N** [comment]
This worked now from current `master` branch. :+1:
