### ISSUE TITLE
QR issue when the password has special characters

### ISSUE THREAD

**Issue by ls-1N** [kokoye2007/wifi-qr#16]
Tested from the newest `master` branch directly, without building a deb file.

Issue when the password has a special character.
The saved QR code contains this information:
```
WIFI:S:go.ted.com/emilynagoski;P:YoKGhQGERB@KVHQSiCrpt

YoKGhQGERB@KVHQSiCrpt;T:WPA;;
```
The SSID is correct. The password is correct but duplicated and has 2 newlines between the duplicates.

**Comment by kokoye2007** [comment]
I need to takedown from mentor and check again.

**Comment by kokoye2007** [comment]
Its my bad.
My pushing is wrong branch and tag,
after that i merge into master :( 
Thanks @ls-1N 

![Screenshot from 2023-04-20 17-39-39](https://user-images.githubusercontent.com/3091754/233349211-c5cc4477-8719-47bb-9603-5d1c5dabf5bb.png)

Here is generate from update.
![wifi-qr-gotedcomemilynagoski](https://user-images.githubusercontent.com/3091754/233349390-f51b5710-df2c-40b0-b466-a9e2e7362dc3.png)

**Comment by ls-1N** [comment]
This issue is still present for me on current `master`.

The information encoded in the QR code that `wifi-qr` saved for me this time:
```
WIFI:S:go.ted.com/emilynagoski

go.ted.com/emilynagoski;P:YoKGhQGERB@KVHQSiCrpt

YoKGhQGERB@KVHQSiCrpt;T:WPA;;;
```

Expected:
```
WIFI:S:go.ted.com/emilynagoskiP:YoKGhQGERB@KVHQSiCrpt;T:WPA;;;
```

**Comment by ls-1N** [comment]
Maybe the problem was also related to my configuration. :woman_shrugging: 
It was not working, but when I deleted the saved wifi configuration and re-added it, it started working as expected now.
