### ISSUE TITLE
QR issue when the name and SSID differ

### ISSUE THREAD

**Issue by ls-1N** [kokoye2007/wifi-qr#17]
Tested from the newest `master` branch directly, without building a deb file.

A wifi network can have a name. The name is usually the same as SSID. But the user can change the name to be different from SSID.

When generating a QR code from such a saved network, the QR code contains the name, not the actual SSID.

IMO the wifi list in zenity should have names, but the generated QR code should use SSID.

**Comment by ls-1N** [comment]
Btw I'm writing these issues because I truly value and appreciate your work on this 😊. I use your app frequently!

**Comment by kokoye2007** [comment]
@ls-1N can you test again for me?

**Comment by ls-1N** [comment]
This worked as expected now from current `master` branch. :+1:
