### ISSUE TITLE
Xiaomi QR code is parsed incorrectly

### ISSUE THREAD

**Issue by Pipeliner** [kokoye2007/wifi-qr#18]
The QR data has the following format: `QR-Code:WIFI:T:WPA;P:MYPASSWORD;S:MYSSID;H:false;` which currently parses as `SSID:<empty>`, `PASS:MYPASSWORD,S:MYSSID`.

**Comment by kokoye2007** [comment]
Thank for your report.
Its possible with strip format and I will update ASAP.

**Comment by kokoye2007** [comment]
If you don't mind,
Please testing with this branch 
https://github.com/kokoye2007/wifi-qr/tree/18-xiaomi-qr-code-is-parsed-incorrectly

**Comment by Pipeliner** [comment]
Thank you for the quick fix! This version worked correctly.


вс, 21 мая 2023 г. в 20:28, kokoye2007 ***@***.***>:
