### ISSUE TITLE
unknow or need to add key-mgmt type for WPA3-PSK

### ISSUE THREAD

**Issue by disposableone** [kokoye2007/wifi-qr#20]
On Gnome 43 trying to add WPA3-PSK wifi network. Gives me "unknow or need to add key-mgmt type".

**Comment by kokoye2007** [comment]
Let me test with WPA3 
Thanks! 

> On Gnome 43 trying to add WPA3-PSK wifi network. Gives me "unknow or need to add key-mgmt type".
