### ISSUE TITLE
QR scan with webcam?

### ISSUE THREAD

**Issue by Thatoo** [kokoye2007/wifi-qr#25]
Hello,

When I launch `wifi-qr -s` a new window appear with the title "zbar barcode reader" but it doesn't do anything. It remain a black window.
My webcam doesn't switch on as if it didn't receive any request.

**Comment by kokoye2007** [comment]
# TODO

- check webcam list

if multiple webcam
- select from list
- set default

**Comment by geokats7** [comment]
On my laptop, it worked like a charm! I'm using Ubuntu 22.04 Jammy
My only comment: The dash `-` is not needed before the various options (which is weird in terms of UX).

**Comment by kokoye2007** [comment]
NOTE: Additional - v4l2-ctrl

https://github.com/kokoye2007/wifi-qr/tree/webcam_v4l2-ctl

**Comment by kokoye2007** [comment]
NOTE: sysdev, sysfs, dev

https://github.com/kokoye2007/wifi-qr/tree/webcam_sysdev
