### ISSUE TITLE
Installation on Fedora 

### ISSUE THREAD

**Issue by lamyergeier** [kokoye2007/wifi-qr#31]
How to install it on Fedora 41?

**Comment by kokoye2007** [comment]
It's based on a Bash script that uses:

- nmcli
- zenity

Generally, you can git pull and run it similar to the approach described in this AskUbuntu thread:
https://askubuntu.com/questions/1470379/how-can-i-scan-a-qr-code-to-connect-to-a-wi-fi-network-on-ubuntu
Give me a day. I will create a Makefile with `make rpm` and `wifi-qr.rpm` package for you.
