### ISSUE TITLE
Need improvements

### ISSUE THREAD

**Issue by naing2victor** [kokoye2007/wifi-qr#6]
1. zbar scanner not terminate on clicking close button without scanning
2. Bad array subscript : wifiqrcred+=([$(echo "$wifiqrdata" | awk -F';' '{print $4}' | cut -d":" -f1)]=$(echo "$wifiqrdata" | awk -F';' '{print $4}' | cut -d":" -f2))   in call_wifi_scan function

**Comment by kokoye2007** [comment]
yes, zbar is just open and print, 
Just found self kill for when detect Scan Data.
+ need to fix

**Comment by kokoye2007** [comment]
yes, zbar is just open and print, 
Just found self kill for when detect Scan Data.
+ need to fix 

no 2, need to recheck
