### ISSUE TITLE
Sudo on the CLI is not mandatory

### ISSUE THREAD

**Issue by baco** [kokoye2007/wifi-qr#8]
The README says to run all the commands with `sudo` prefix. That, actually depends on the permissions your operating system provides to the user and is not a mandatory pre-command.

Actually, on Debian, it works perfectly if you have access to select and connect to new WiFi networks, which is a default permission any average user has.

It is not polite to recommend authority escalation on documentation when not needed.

**Comment by kokoye2007** [comment]
Thank for this issue.
I write very first time at bash with cat grep awk with etc/networkmanager/system-connections

It's need sudo user mode.

So I am using sudo and gui base at pkexec.

0.1-2 is fully nmcli 
It's no need sudo and policy pkexec. 

README is need to update.

Current WiFi-QR is no need sudo.


With regards
